import type { TileDefinition } from '../types/game';

// Official Hungarian Scrabble tile distribution (100 tiles)
// Includes digraph tiles (CS, GY, LY, NY, SZ, TY, ZS) — each is one tile
export const TILES_HU: TileDefinition[] = [
  { letter: '', points: 0, count: 2 },     // Blanks
  { letter: 'A', points: 1, count: 6 },
  { letter: 'Á', points: 1, count: 4 },
  { letter: 'B', points: 2, count: 3 },
  { letter: 'C', points: 5, count: 1 },
  { letter: 'CS', points: 7, count: 1 },
  { letter: 'D', points: 2, count: 3 },
  { letter: 'E', points: 1, count: 6 },
  { letter: 'É', points: 3, count: 3 },
  { letter: 'F', points: 4, count: 2 },
  { letter: 'G', points: 2, count: 3 },
  { letter: 'GY', points: 4, count: 2 },
  { letter: 'H', points: 3, count: 2 },
  { letter: 'I', points: 1, count: 3 },
  { letter: 'Í', points: 5, count: 1 },
  { letter: 'J', points: 4, count: 2 },
  { letter: 'K', points: 1, count: 6 },
  { letter: 'L', points: 1, count: 4 },
  { letter: 'LY', points: 8, count: 1 },
  { letter: 'M', points: 1, count: 3 },
  { letter: 'N', points: 1, count: 4 },
  { letter: 'NY', points: 5, count: 1 },
  { letter: 'O', points: 1, count: 3 },
  { letter: 'Ó', points: 2, count: 3 },
  { letter: 'Ö', points: 4, count: 2 },
  { letter: 'Ő', points: 7, count: 1 },
  { letter: 'P', points: 4, count: 2 },
  { letter: 'R', points: 1, count: 4 },
  { letter: 'S', points: 1, count: 3 },
  { letter: 'SZ', points: 3, count: 2 },
  { letter: 'T', points: 1, count: 5 },
  { letter: 'TY', points: 10, count: 1 },
  { letter: 'U', points: 4, count: 2 },
  { letter: 'Ú', points: 7, count: 1 },
  { letter: 'Ü', points: 4, count: 2 },
  { letter: 'Ű', points: 7, count: 1 },
  { letter: 'V', points: 3, count: 2 },
  { letter: 'Z', points: 4, count: 2 },
  { letter: 'ZS', points: 4, count: 1 },
];
